# Generated by Django 3.0.7 on 2020-07-09 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 9, 12, 28, 31, 297091, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='acc_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
